spring:
  application:
    name: foxc-eureka-server
  profiles:
    active: @profiles.active@
  security:
    user:
      name: foxc
      password: foxc_www

logging:
  config: classpath:logback.xml
