server:
  port: 8050
spring:
  application:
    name: foxc-gateway
  cloud:
    gateway:
      routes:
        - id: foxc-provider-user-route
#          uri: http://localhost:8001
          uri: lb://foxc-provider-user
          predicates:
            - Path=/foxc-user/**
#            - Query=accessToken,123.
#            - Query=foxc,web
#            - Method=GET
#            - Header=X-Request-Id, \d+
#            - Cookie=sessionId, test
#            - Host=**.foxc.com.cn
#            - RemoteAddr=192.168.2.1/24
          filters:
            # 截取路径的最前面1个部分（假设访问：http://localhost:8050/foxc-user/user/findById/1，则路由到后端实际地址为：http://foxc-provider-user/user/findById/1）
            - StripPrefix=1
            - name: Hystrix # 使用Hystrix进行服务熔断降级
              args:
                name: fallbackcmd
                fallbackUri: forward:/foxcUserFallBack

# 配置foxcUserFallbackCmd超时熔断时间
#hystrix:
#  command:
#    foxcUserFallbackCmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


eureka:
  client:
    serviceUrl:
      defaultZone: http://foxc:foxc_www@localhost:8801/eureka/
# Actuator API
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: gateway