server:
  port: 8802
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      my-metadata: 我自定义的元数据
  client:
    serviceUrl:
      defaultZone: http://foxc:foxc_www@localhost:8801/eureka/