server:
  port: 8040
spring:
  application:
    name: foxc-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://foxc:foxc_www@localhost:8801/eureka/

# zuul 路由配置
zuul:
  # 配置饥饿加载
  ribbon:
    eager-load:
      enabled: true
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 0
  routes:
    foxc-user:
      path: /foxc-user/**
#      url: http://localhost:8001
      serviceId: foxc-provider-user
    foxc-movie-ribbon:
      path: /foxc-movie-ribbon/**
      serviceId: foxc-consumer-movie-ribbon
    foxc-movie:
      path: /foxc-movie/**
      serviceId: foxc-consumer-movie
    foxc-survey:
      path: /foxc-survey/**
      serviceId: foxc-question-survey
  # zuul忽略所有默认路由，所有服务都需配置路由规则，否则饥饿加载不生效
  ignored-services: /**
  # 开启zuul重试机制
  retryable: true