spring:
  application:
    name: foxc-consumer-movie-feign-customizing
  profiles:
    active: @profiles.active@
  jackson:
    default-property-inclusion: non_null

logging:
  config: classpath:logback.xml
